// The adapter stamps `at <ISO timestamp>` into the bundle banner, which would
// make the committed artifact differ from a rebuild on every byte-compare.
// Drop the timestamp so `bun run build` is reproducible.

const file = 'build/_worker.js';
const source = await Bun.file(file).text();
const normalized = source.replace(
  /^\/\/ Generated by (\S+) v(\S+) at \S+$/m,
  '// Generated by $1 v$2'
);

if (normalized === source) {
  console.error(`banner not found in ${file}`);
  process.exit(1);
}

await Bun.write(file, normalized);
console.log(`normalized ${file} (${normalized.length} bytes)`);
